
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(100) NOT NULL,
  password VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE lessons (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  lang VARCHAR(100) NOT NULL,
  level VARCHAR(100) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE vocabulary (
  id SERIAL PRIMARY KEY,
  value VARCHAR(100) NOT NULL,
  translated VARCHAR(255) NOT NULL,
  lessonId INT REFERENCES lessons (id),
  createdAt TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE sentences (
  id SERIAL PRIMARY KEY,
  value VARCHAR(100) NOT NULL,
  translated VARCHAR(255) NOT NULL,
  lessonId INT REFERENCES lessons (id),
  createdAt TIMESTAMP NOT NULL DEFAULT NOW()
);
