
CREATE TABLE lessons (
  lesson_id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  lang VARCHAR(100) NOT NULL,
  level VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE words (
  word_id SERIAL PRIMARY KEY,
  value VARCHAR(100) NOT NULL,
  translated VARCHAR(255) NOT NULL,
  lesson_id INT REFERENCES lessons (lesson_id) NOT NULL,
  type VARCHAR(10) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
