apiVersion: apps/v1
kind: Deployment
metadata:
  name: vocabulary-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vocabulary
  template:
    metadata:
      labels:
        app: vocabulary
    spec:
      containers:
        - name: vocabulary
          image: cygnetops/vocabulary
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: 'mongodb://vocabulary-mongo-srv:27017/vocabulary'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: vocabulary-srv
spec:
  selector:
    app: vocabulary
  ports:
    - name: vocabulary
      protocol: TCP
      port: 3000
      targetPort: 3000
